<%@ Page Title="" Language="C#" MasterPageFile="~/Staff/Staff.master" AutoEventWireup="true" CodeFile="Upload.aspx.cs" Inherits="Staff_Upload" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .style1
        {
            width: 708px;
        }
    .style2
    {
        text-align: right;
        color: Red;
        width: 137px;
    }
    .style3
    {
        width: 137px;
    }
        .auto-style2 {
            text-align: right;
            color: Red;
            width: 137px;
            height: 26px;
        }
        .auto-style3 {
            height: 26px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table class="tbl">
        <tr>
            <td class="tblhead">
                Upload Materials - Documents</td>
        </tr>
        <tr>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td>
                <table class="style1">
                    <tr>
                        <td class="style2">
                            Title :
                        </td>
                        <td>
                            <asp:TextBox ID="txttitle" runat="server" CssClass="txt"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td class="auto-style2">
                            Upload File :</td>
                        <td class="auto-style3">
                            <asp:FileUpload ID="FileUpload1" runat="server" CssClass="txt" Width="220px" />
                        </td>
                    </tr>
                     <tr>
                        <td class="style2">
                            Course Title :
                        </td>
                        <td>
                            <asp:TextBox ID="txtcourse" runat="server" CssClass="txt"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td class="style3">
                            &nbsp;</td>
                        <td>
                            <asp:Button ID="Button12" runat="server" CssClass="btn" 
                                onclick="Button12_Click" Text="Upload" />
                        </td>
                    </tr>
                    <tr>
                        <td class="style3">
                            &nbsp;</td>
                        <td>
                            <asp:Label ID="lblsave" runat="server"></asp:Label>
                        </td>
                    </tr>
                    <tr>
                        <td class="style3">
                            &nbsp;</td>
                        <td>
                            <asp:Label ID="lbl" runat="server" ForeColor="#660066"></asp:Label>
                        </td>
                    </tr>
                    <tr>
                        <td class="style3">
                            &nbsp;</td>
                        <td>
                            <asp:GridView ID="GridView4" runat="server" AutoGenerateColumns="False" 
                                AutoGenerateDeleteButton="True" CellPadding="4" DataKeyNames="uid" 
                                ForeColor="#333333" GridLines="None" onrowdeleting="GridView4_RowDeleting" 
                                onrowcommand="GridView4_RowCommand" Width="551px">
                                <AlternatingRowStyle BackColor="White" />
                                <Columns>
                                    <asp:BoundField DataField="Title" HeaderText="Title" />
                                    <asp:BoundField DataField="Upload" HeaderText="FileName" />
                                    <asp:BoundField DataField="Download" HeaderText="Download" />
                                   
                                    <asp:TemplateField HeaderText="Status">
                                    <ItemTemplate>
                                    <asp:LinkButton runat="server" Text='<%#Eval("Status") %>' Font-Bold="true" ID="lnkstatus" CommandName="a" CommandArgument='<%#Eval("UID") %>'></asp:LinkButton>
                                    </ItemTemplate>
                                    </asp:TemplateField>
                                   
                                </Columns>
                                <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                                <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                                <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                                <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                                <SortedAscendingCellStyle BackColor="#FDF5AC" />
                                <SortedAscendingHeaderStyle BackColor="#4D0000" />
                                <SortedDescendingCellStyle BackColor="#FCF6C0" />
                                <SortedDescendingHeaderStyle BackColor="#820000" />
                            </asp:GridView>
                        </td>
                    </tr>
                    <tr>
                        <td class="style3">
                            &nbsp;</td>
                        <td>
                            &nbsp;</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;</td>
        </tr>
    </table>
</asp:Content>

